name: Build Axel for ImmortalWrt

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-axel:
    name: Build Axel Package
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [ "x86_64", "mediatek_filogic" ]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
      if: matrix.platform == 'mediatek_filogic'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libncurses-dev \
          zlib1g-dev \
          gawk \
          git \
          gettext \
          libssl-dev \
          rsync \
          wget \
          unzip \
          zstd \
          python3 \
          jq \
          autoconf \
          automake \
          libtool \
          file \
          pkg-config
    
    - name: Set SDK URLs
      id: set-sdk
      run: |
        if [ "${{ matrix.platform }}" = "x86_64" ]; then
          echo "sdk_url=https://downloads.immortalwrt.org/releases/24.10.2/targets/x86/64/immortalwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst" >> $GITHUB_OUTPUT
        elif [ "${{ matrix.platform }}" = "mediatek_filogic" ]; then
          echo "sdk_url=https://downloads.immortalwrt.org/releases/24.10.2/targets/mediatek/filogic/immortalwrt-sdk-24.10.2-mediatek-filogic_gcc-13.3.0_musl.Linux-x86_64.tar.zst" >> $GITHUB_OUTPUT
        fi
    
    - name: Download and extract SDK
      run: |
        mkdir -p sdk-${{ matrix.platform }}
        wget ${{ steps.set-sdk.outputs.sdk_url }} -O sdk.tar.zst
        tar -xaf sdk.tar.zst -C sdk-${{ matrix.platform }} --strip-components=1
        rm sdk.tar.zst
    
    - name: Prepare package directory
      run: |
        mkdir -p sdk-${{ matrix.platform }}/package/axel
        cp -R package/axel/Makefile sdk-${{ matrix.platform }}/package/axel/

    - name: Set up SDK environment
      run: |
        cd sdk-${{ matrix.platform }}
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
    
    - name: Debug - Check OpenSSL
      run: |
        cd sdk-${{ matrix.platform }}
        echo "STAGING_DIR: $(pwd)/staging_dir"
        find staging_dir -name ssl.h || true
        find staging_dir -name libssl.so || true
        find staging_dir -name openssl.pc || true
    
    - name: Build axel package
      run: |
        cd sdk-${{ matrix.platform }}
        make package/axel/compile V=s -j$(nproc)
    
    - name: Collect artifacts
      run: |
        mkdir -p artifacts
        
        # 查找 IPK 文件
        find sdk-${{ matrix.platform }} -name "axel_*.ipk" -exec cp {} artifacts/axel-${{ matrix.platform }}.ipk \;
        
        # 验证文件存在
        if [ ! -f artifacts/axel-${{ matrix.platform }}.ipk ]; then
          echo "##[error]No IPK file found for ${{ matrix.platform }}"
          find sdk-${{ matrix.platform }} -name "axel*" -o -name "*.ipk" || true
          exit 1
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: axel-${{ matrix.platform }}-package
        path: artifacts/axel-${{ matrix.platform }}.ipk
        retention-days: 7

  release:
    name: Create Release
    runs-on: ubuntu-22.04
    needs: build-axel
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: axel-*-package
        merge-multiple: true
    
    - name: List downloaded artifacts
      run: ls -lh artifacts
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/axel-*.ipk
        tag_name: ${{ github.ref }}
        body: "Axel download accelerator built for ImmortalWrt"
        generate_release_notes: true
